# Numpy Notes

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3],dtype='int8')
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [4]:
# Print Matrix
print(a)
print(b)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
# Get Dimension
print("Dimension",b.ndim)

Dimension 2


In [6]:
# Get Type/Size
a.dtype

dtype('int8')

In [7]:
# GetShape
b.shape

(2, 3)

In [8]:
#get Size(how many bits)
a.itemsize

1

In [9]:
# Get total size ( a.size * a.item size)
a.nbytes

3

Accessing/Changing Specific elements, rows,columns,etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [11]:
# get a specific element from the array

a[0,2]

3

In [12]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# get a specific column
a[:,2]

array([ 3, 10])

In [14]:
# [start:end and step size]
a[0, 1:6:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20
print(a)

a[:,2] = [3,4]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9  4 11 12 20 14]]


In [16]:
#3d array
b = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [17]:
# get specific with array
b[0,1,2]

7

In [18]:
# replace 

print(b[0,1,0:2],b[1,0,0:2])

[5 6] [ 9 10]


In [19]:
#Initializing Different Types of Arrays
np.zeros(5)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
d = np.ones((4,2,2))
d

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [21]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [22]:
np.full_like(d,4)

array([[[4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.]]])

In [23]:
# random decimal number
np.random.rand(4,2)

array([[0.17164692, 0.58775398],
       [0.67511081, 0.8253342 ],
       [0.23127767, 0.21562014],
       [0.1662318 , 0.88901445]])

In [24]:
np.random.random_sample(d.shape)

array([[[0.77362021, 0.52406917],
        [0.82920408, 0.25579862]],

       [[0.94525561, 0.72808095],
        [0.75961852, 0.85647701]],

       [[0.64997233, 0.28368725],
        [0.35181986, 0.79724105]],

       [[0.8350899 , 0.29489347],
        [0.63642072, 0.74693576]]])

In [25]:
# random integer value
np.random.randint(4,7,size=(3,3))

array([[6, 5, 5],
       [4, 6, 6],
       [5, 5, 5]])

In [26]:
#identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr= np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [28]:
a = np.ones((5,5))
a[1:4,1:4]=0
a[2,2] = 9
b = a.astype(int)
b

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [29]:
#Mathematics

a = np.array([1,2,3,4])
a +2
a - 3
a /3


array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [30]:
b = np.array([1,2,3,4])
a+b

array([2, 4, 6, 8])

In [31]:
a ** 2

array([ 1,  4,  9, 16])

In [32]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [33]:
# Linear Algebra
a = np.full((2,3),1)
print(a)

b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [34]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [35]:
### Statistics

np.min(a,axis=0)

array([1, 1, 1])

In [36]:
np.max(a,axis=0)

array([1, 1, 1])

In [37]:
np.sum(a)

6

In [40]:
#Reorganizing Arrays
befor= np.array([[1,2,3,4],[5,6,7,8]])

after = befor.reshape((4,2))
print(after)
after[[1,3],:]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


array([[3, 4],
       [7, 8]])

In [ ]:
# vertically stacking
v1 = np.array([1,2,3,4])
v2 = np.array([3,4,5,6])
np.vstack([v1,v2])


In [43]:
# horizontal Stacking
h1 = np.array([1,2,3,4])
h2 = np.array([3,4,5,6])

np.hstack((h1,h2))

array([1, 2, 3, 4, 3, 4, 5, 6])

In [ ]:
#Miscellaneous
#Load Data from the file
# np.genfromtxt('data.txt',delimiter= ",")
# filedata.astype('int32')


In [ ]:
#Boolean Masking and Advanced Indexing
h1 > 50

In [ ]:
h1[h1<2]# it will give the array because [h1<2] provides an index

In [44]:
np.any(h1> 3,axis=0)
np.all(h1> 3,axis =0)

True

In [46]:
h1[[1,2,3]]

array([2, 3, 4])

In [47]:
(~((h2 >1) & (h1 <3)))

array([False, False,  True,  True])

In [55]:
a = np.arange(1,31).reshape((6,5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [60]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [61]:
a[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])